force-app/main/default/objects/TestDynamicFields__c/TestDynamicFields__c.object-meta.xml
<CustomObject>
    <label>TestDynamicFields</label>
    <nameField>
        <label>TestDynamicFields Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TestDynamicFields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TestDynamicFields__c/fields/Picklist1__c.field-meta.xml
<CustomField>
    <fullName>Picklist1__c</fullName>
    <label>Picklist1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Value1</fullName>
            </value>
            <value>
                <fullName>Value2</fullName>
            </value>
            <value>
                <fullName>Value3</fullName>
            </value>
            <value>
                <fullName>Value4</fullName>
            </value>
            <value>
                <fullName>Value5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TestDynamicFields__c/fields/Picklist2__c.field-meta.xml
<CustomField>
    <fullName>Picklist2__c</fullName>
    <label>Picklist2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Value1</fullName>
            </value>
            <value>
                <fullName>Value2</fullName>
            </value>
            <value>
                <fullName>Value3</fullName>
            </value>
            <value>
                <fullName>Value4</fullName>
            </value>
            <value>
                <fullName>Value5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TestDynamicFields__c/fields/Show1__c.field-meta.xml
<CustomField>
    <fullName>Show1__c</fullName>
    <label>Show1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TestDynamicFields__c/fields/Show2__c.field-meta.xml
<CustomField>
    <fullName>Show2__c</fullName>
    <label>Show2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TestDynamicFields__c/fields/Show3__c.field-meta.xml
<CustomField>
    <fullName>Show3__c</fullName>
    <label>Show3</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TestDynamicFields__c/fields/Show4__c.field-meta.xml
<CustomField>
    <fullName>Show4__c</fullName>
    <label>Show4</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TestDynamicFields__c/fields/Show5__c.field-meta.xml
<CustomField>
    <fullName>Show5__c</fullName>
    <label>Show5</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BlankFieldsTriggerHelperTest.cls
@IsTest(SeeAllData=true)
public class BlankFieldsTriggerHelperTest {

    // TODO: make this a legit test, this is only to get it into my dev org
    static testmethod void runPositiveTestCases() {

        String selectedObject = 'TestDynamicFields__c';

        try {
            List<String> fieldsToCheck = BlankFieldsTriggerHelper.getFieldsToCheck('Picklist1__c=Value1,Picklist2__c=Value1,');

            TestDynamicFields__c new_o = new TestDynamicFields__c();
            new_o.Name = 'Apex Test';
            insert new_o;

            new_o.Picklist1__c = 'Value1';
            new_o.Picklist2__c = 'Value1';
            new_o.Show1__c = 'Show1a';
            new_o.Show2__c = 'Show2a';
            new_o.Show3__c = 'Show3a';
            new_o.Show4__c = 'Show4a';
            new_o.Show5__c = 'Show5a';
            update new_o;

            new_o.Picklist1__c = 'Value2';
            new_o.Picklist2__c = 'Value2';
            new_o.Show1__c = 'Show1b';
            new_o.Show2__c = 'Show2b';
            new_o.Show3__c = 'Show3b';
            new_o.Show4__c = 'Show4b';
            new_o.Show5__c = 'Show5b';
            update new_o;

            TestDynamicFields__c old_o = new TestDynamicFields__c();
    
            String fieldsValues = BlankFieldsTriggerHelper.getFieldsValues(selectedObject, fieldsToCheck, new_o, old_o);

        } catch(DmlException e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
        }

        System.assertEquals(true,true, 'BlankFieldsTriggerHelperTest success');
    }
}